name: EdgeCore
version: beta_4.1
author: Panjab
authors: [lush,horoking,Exodevil, ase34]
website: http://edgecraft.de

load: STARTUP
loadbefore: [EdgeConomy, EdgeCuboid, EdgeJobs]

main: net.edgecraft.edgecore.EdgeCore
