name: EdgeCore
version: 3.5
author: Panjab
authors: [lush,horoking,Exodevil]
website: http://edgecraft.de

main: net.edgecraft.edgecore.EdgeCore

commands:
    db:
      description: Database Command
      aliases: ['database', 'sql']
    language:
      description: Language Command
      aliases: ['lang']
    system:
      description: System Command
      aliases: ['sys']
    user:
      description: User Command
    who:
      description: Who Command
      aliases: ['list']
