name: EdgeCore
version: beta_3.7
author: Panjab
authors: [lush,horoking,Exodevil]
website: http://edgecraft.de

load: STARTUP
loadbefore: [EdgeConomy, EdgeCuboid, EdgeJobs]

main: net.edgecraft.edgecore.EdgeCore
