name: EdgeCraft
version: 2.3
author: Panjab
authors: [lush]
website: http://edgecraft.de

main: net.edgecraft.edgecraft.EdgeCraft

commands:
    db:
      description: Database Command
      aliases: ['database', 'sql']
    language:
      description: Language Command
      aliases: ['lang']
    system:
      description: System Command
	aliases: ['sys']
    user:
      description: User Command
    who:
      description: Who Command
      aliases: ['list']
